[package]
name = "binary-search"
version = "0.1.2"
authors = ["Daniel Waterworth <me@danielwaterworth.com>"]
edition = "2018"
license = "MIT"
description = "General binary search implementation"
readme = "README.md"
repository = "https://github.com/danielwaterworth/binary-search"

[dependencies]
