[package]
name = "binary-search"
version = "0.1.1"
authors = ["Daniel Waterworth <me@danielwaterworth.com>"]
edition = "2018"
license = "MIT"
description = "General binary search implementation"
readme = "README.md"

[dependencies]
